//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.FACULTADD = new HashSet<FACULTADD>();
        }
    
        public int ID_Ciudad { get; set; }
        public string ciudad1 { get; set; }
        public int estado { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<FACULTADD> FACULTADD { get; set; }
    }
}
